Plumbing
Lafiction/BootstrapPlumbing pull request #1
Opened 2018-03-30 06:03 UTC by Lafiction

2018-03-30 14:08 UTC, olga-demchuk requested changes

2018-03-30 14:08 UTC, olga-demchuk commented on css/style.css
> +  float: left;
Подскажи, пожалуйста, для чего здесь использован `float: left;`?

2018-03-30 14:08 UTC, olga-demchuk commented on index.html
> +                  <li class="dropdown"><a href="blog.html" class="nav-link">Blog</a>
Просьба выполнить правку:
при перемещении курсора по выпадающему меню `Blog / Blog1` пункт меню `Blog` должен быть подсвечен чёрным.
<img width="1043" alt="screen shot 2018-03-30 at 12 39 11" src="https://user-images.githubusercontent.com/926439/38133410-c272397a-3417-11e8-9672-b859b28b6975.png">

2018-03-30 14:08 UTC, olga-demchuk commented on index.html
> +            <input type="textarea" name="textarea" placeholder="description of work or services needed">
Почему здесь использован `<input type="textarea" ...>`?
<img width="728" alt="screen shot 2018-03-30 at 12 41 33" src="https://user-images.githubusercontent.com/926439/38133393-b40b49f8-3417-11e8-903c-9464cb887e25.png">

2018-03-30 14:08 UTC, olga-demchuk commented on css/style.css
> +body {
Просьба выполнить следующую доработку:
**на мобильных устройствах**
- В `.top-area` слоган прижат к левому краю, соц. иконки - к правому
- логотип и контактные данные выровнены по центру
- в форме в `.top-section` поля name и phone растянуты на 100%
<img width="610" alt="plumbing 2018-03-30 12-42-51 1" src="https://user-images.githubusercontent.com/926439/38133645-c261d9ee-3418-11e8-8dde-8608e2a1be0c.png">

2018-04-01 14:44 UTC, Lafiction commented on css/style.css
> +  float: left;
float: left не нужен, удалила

2018-04-01 14:47 UTC, Lafiction commented on index.html
> +            <input type="textarea" name="textarea" placeholder="description of work or services needed">
Ошиблась, заменила на <textarea>, сейчас переносится на новую строку.

2018-04-01 14:49 UTC, Lafiction commented on index.html
> +                  <li class="dropdown"><a href="blog.html" class="nav-link">Blog</a>
Это добавила.

2018-04-01 14:50 UTC, Lafiction commented on css/style.css
> +body {
И это тоже.

2018-04-28 09:17 UTC, merged